pg:
  service:
    numReplicas: 1
    type: NodePort
    containerPort: 5432
    nodePort: 30003
  volume:
    size: 1G
    hostMountPath: /.db_data # OVERRIDDEN IN HELMFILE TO BE $GIT_ROOT/.db_data

backend:
  service:
    image: registry.gitlab.com/bigboiblue/kblue-io-registry/backend-dev:latest
    numReplicas: 1
    containerPort: 8080
    resources:
      isHardLimit: false
    allowedOrigins:
      - "https://www.kblue-dev.io"
  ingress:
    useStagingIssuer: true
    host: api.kblue-dev.io
    rps: 10000


frontend:
  service:
    image: registry.gitlab.com/bigboiblue/kblue-io-registry/frontend-dev:latest
    numReplicas: 1
    containerPort: 3000
    resources:
      isHardLimit: false
      memory: "1G"
      cpu: "1"
  ingress:
    useStagingIssuer: true
    bareDomain: kblue-dev.io
    host: www.kblue-dev.io
    rps: 10000

