pg:
  service:
    numReplicas: 1
    type: NodePort
    nodePort: 5432
    envVars:
      ENVIRONMENT: dev

  volume:
    size: 1G
    hostMountPath: /.db_data # OVERRIDDEN IN HELMFILE TO BE $GIT_ROOT/.db_data

backend:
  service:
    image: registry.gitlab.com/bigboiblue/kblue-io-registry/backend-dev:latest
    numReplicas: 1
    containerPort: 8080

  ingress:
    useStagingIssuer: true
    host: api.kblue-dev.io
    rps: 10000
