pg:
  service:
    numReplicas: 1
    type: ClusterIP
  volume:
    size: 10G
    hostMountPath: /.db_data # OVERRIDDEN IN HELMFILE TO BE $HOME/.db_data

backend:
  service:
    image: registry.gitlab.com/bigboiblue/kblue-io-registry/backend:latest
    numReplicas: 1
    containerPort: 8080
  ingress:
    useStagingIssuer: true
    host: api.kblue.io
    rps: 20

frontend:
  service:
    image: registry.gitlab.com/bigboiblue/kblue-io-registry/frontend:latest
    numReplicas: 1
    containerPort: 80
  ingress:
    useStagingIssuer: true
    host: www.kblue.io
    rps: 20
