apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    name: cert-manager
---

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: letsencrypt-staging-issuer
 namespace: cert-manager
spec:
 acme:
   # The ACME server URL
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: kyle.blue.nuttall@gmail.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: staging-cert
   # Enable the HTTP-01 challenge provider
   solvers:
   - http01:
       ingress:
         class:  nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-issuer
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: kyle.blue.nuttall@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: prod-cert
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx