# Configuring container runtime cgroup driver
# See https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/
# Patches to listen on / bind to 127.0.0.1 (localhost). Don't try and bind to private network machine ip
# We don't need this accessible from network, and it breaks when you change network

kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.28.2
networking:
  podSubnet: "192.168.0.0/16"
apiServer:
  extraArgs:
    service-node-port-range: 80-32767
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
patches:
  directory: "./kubernetes/kubeadm/patches"