apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ include "app-namespace" . }}
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.service.numReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ .Values.service.name }}
          image: {{ .Values.service.image }}
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: {{ include "environment" . }}
            {{- range $key, $value := .Values.service.envVars }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          resources: 
            {{ if eq .Values.service.resources.isHardLimit true }}limits{{ else }}requests{{ end }}:
              memory: {{ .Values.service.resources.memory }}
              cpu: {{ .Values.service.resources.cpu }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            {{- if eq (include "environment" .) "dev" }}
            - name: ca-bundle
              mountPath: /etc/ssl/certs/ca.crt
              subPath: ca.crt
            {{- end }}
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf-frontend
            items:
              - key: nginx.conf
                path: nginx.conf
        {{- if eq (include "environment" .) "dev" }}
        - name: ca-bundle
          configMap:
            # ca-bundle made by trust-manager which holds trusted certificate authority (CA) public keys
            name: {{ include "ca-bundle-name" . }}
        {{- end }}
