apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ include "app-namespace" . }}
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
  - port: 80
    targetPort: {{ .Values.service.containerPort }}
