apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-config
  namespace: {{ .Values.namespace }}
  labels:
    app: postgresql
data:
  POSTGRES_DB: kblue
  POSTGRES_USER: cluster-admin
  POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 --auth-local=scram-sha-256