apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
  labels:
    app: postgresql
spec: 
  type: {{ .Values.service.type }}
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
