apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ include "app-namespace" . }}
  labels:
    app: postgresql
spec: 
  type: {{ .Values.service.type }}
  selector:
    app: postgresql
  ports:
  - port: {{ .Values.service.containerPort }}
    targetPort: {{ .Values.service.containerPort }}
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
