# Deploy with:
#    helmfile apply -e dev
#    helmfile apply -e prod

hooks:
  - name: ensure-secrets-exist
    events: ["prepare"]
    command: bash
    args: ["-c", "./prepare-hook.sh {{`{{.Environment.Name}}`}}"]

environments:
  dev: {}
  prod: {}

releases:
  - name: calico
    chart: ./tigera-operator

  - name: app
    chart: ./app
    needs: ["calico", "cluster-config"]
    labels:
      env: "{{ .Environment.Name }}"
    values:
      - globals.yaml
      - global: {environment: {{ .Environment.Name }}}
      - "app/values-{{ .Environment.Name }}.yaml"
      - pg:
          volume:
            hostMountPath: |
              {{- if eq .Environment.Name "prod" }}
                {{ requiredEnv "HOME" | trim }}/.db_data
              {{- else }}
                {{ exec "bash" (list "-c" "git rev-parse --show-toplevel") | trim }}/.db_data
              {{- end }}

  - name: cluster-config
    chart: ./cluster-config
    needs: ["calico"]
    labels:
      env: "{{ .Environment.Name }}"
    values:
      - globals.yaml
      - global: {environment: {{ .Environment.Name }}}
      - "cluster-config/values-{{ .Environment.Name }}.yaml"
