# Deploy a certain environment with:
#    helmfile apply -l env=dev
# Deploy only one release with:
#    helmfile apply -l name=dev-app

releases:
  - name: dev-app
    chart: ./app
    labels:
      env: dev

  - name: prod-app
    chart: ./app
    labels:
      env: prod

  - name: dev-cluster-config
    chart: ./cluster-config
    labels:
      env: dev
    values:
      - cluster-config/values-dev.yaml

  - name: prod-cluster-config
    chart: ./cluster-config
    labels:
      env: prod
    values:
      - cluster-config/values-prod.yaml
