# Deploy a certain environment with:
#    helmfile apply -l env=dev
# Deploy only one release with:
#    helmfile apply -l name=dev-app


hooks:
  - name: ensure-secrets-exist
    events: ["prepare"]
    command: bash
    args: ["-c", "./prepare-hook.sh"]

releases:
  - name: dev-app
    chart: ./app
    labels:
      env: dev
    values:
      - globals.yaml
      - global:
          environment: dev
      - app/values-dev.yaml
      - pg:
          volume:
            hostMountPath: "{{ exec "bash" (list "-c" "git rev-parse --show-toplevel") | trim}}/.db_data"

  - name: prod-app
    chart: ./app
    labels:
      env: prod
    values:
      - globals.yaml
      - app/values-prod.yaml
      - pg:
          volume:
            hostMountPath: {{ requiredEnv "HOME" | trim }}/.db_data

  - name: dev-cluster-config
    chart: ./cluster-config
    labels:
      env: dev
    values:
      - globals.yaml
      - global:
          environment: dev
      - cluster-config/values-dev.yaml

  - name: prod-cluster-config
    chart: ./cluster-config
    labels:
      env: prod
    values:
      - globals.yaml
      - cluster-config/values-prod.yaml
